### ISSUE TITLE
got an Raw data of aausat-4 and wanted to demodulate  and decoder it 

### ISSUE THREAD

**Issue by YYCchen6666** [daniestevez/gr-satellites#31] opened 2019-01-19 17:21 UTC
Hi ,I got an raw data of assist-4 but didn’t know how to demodulate it , I tryed use the  fm mod of gr-frontends referred on your article to demodulate it and then put the data in to the decode grc but failed at last  ,can you help me ?

**Comment by daniestevez** [comment] 2019-01-30 19:33
Have you tried first with the sample AAUSAT-4 recording from [satellite-recordings](https://github.com/daniestevez/satellite-recordings)?

**Comment by daniestevez** [comment] 2019-03-02 08:16
Closing this, as it is not a bug and it's being one month without additional input.

**Closed by daniestevez** 2019-03-02 08:16 UTC
